### ISSUE TITLE
Unable to edit ontlogies

### ISSUE THREAD

**Issue by nikhitajatain** [Novartis/ontobrowser#5]
Hi Carlo,

I am working with ontobrowser and I have uploaded ontologies and codelists. But I am unable to edit them directly from the ontobrowser. I am not getting the options to edit the content or to add synonyms and add relationship. Kindly help me with this. I have atached the Screenshot of my ontobrowser.

Thank you,
Nikhita 
Erasmus MC.

![ontobrowser](https://user-images.githubusercontent.com/43199134/62861377-9abadd80-bd03-11e9-8bea-e2e9a6628431.png)

**Comment by carloravagli** [comment]
Please ensure that you have created a curator: https://github.com/Novartis/ontobrowser/blob/master/doc/INSTALL.md#add-a-curator

**Comment by nikhitajatain** [comment]
Hi Carlo,
I already created that curator, but still it is in visualization form not in editing form.

Thanks,
Nikhita

**Comment by carloravagli** [comment]
In that case, it sounds like the curator username is not being passed from Apache to Wildfly.  I suspect something has changed (since I wrote the install docs) in the newer versions of Wildfly (and/or Apache AJP). Others had the same issue. 

When accessing the OntoBrowser GUI, can you please check the Wildfly server.log file for an info message: Loading curator: username. If username is null then OntoBrowser is not receiving the username from Apache. 

Another user added the following code to OntoBrowserServiceImpl.java. I’m not sure why they had to do this, when using mod_proxy_ajp the username should be available via the getRemoteUser() method. Not sure if they setup the proxy calls via http (instead of AJP)?
 
```
private String getUsername() {
       HttpServletRequest request = getThreadLocalRequest();
       String username = request.getRemoteUser();
       // Temp workaround to the apache --> wildfly bridge
       if(username == null) {
              username = request.getHeader("REMOTE_USER");
       }
             
       if(username == null) {
              Principal principal = request.getUserPrincipal();
              if(principal != null) {
                     username = principal.getName();
              }
       }
       
       return username;
}
```

**Comment by nikhitajatain** [comment]
Hi Carlo,

Thanku very much for your help. 

Thanks,
Nikhita
